#Github_Actions
name: Test Project
on:
    push:
        branches:
            - main
jobs:
    checkout-code:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Buid NodeJS
              run: npm install
            - name: Test NodeJS
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        needs: checkout-code
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Buid NodeJS
              run: npm install
            - name: Build Project
              run: npm run build
            - name: Deploy
              run: echo "Deploying..."
    publish:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Buid NodeJS
              run: npm install
            - name: Build Project
              run: npm run build
            - name: Deploy
              uses: JS-DevTools/npm-publish@v1
              with:
                token: ${{ secrets.NPM_TOKEN }}
